name: "Infrastructure Deployment"

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    name: "Deploy Staging"
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: ./infrastructure/environments/staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

  deploy-production:
    name: "Deploy Production"
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./infrastructure/environments/production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
